project:
  type: website
  output-dir: "docs/"
  resources: 
    - "*.pdf"
    - "img/*"
    - "*.pptx"
    - "template_submissao.docx"

website:
  # body-header: |
  #   ![Logo image](/img/logo.jpeg)
  title: "V SICAM"
  page-footer:
    center: "V Simpósio Interdisciplinar de Ciência Ambiental - 2024" 
    border: true
    background: dark
    right: 
      - icon: house
        href: "https://sicam.com.br"
      - icon: instagram
        href: https://www.instagram.com/sicam_procam_usp/
      - icon: linkedin
        href: "https://www.linkedin.com/in/v-sicam-simp%C3%B3sio-interdisciplinar-de-ci%C3%AAncia-ambiental-a84079319/"
      - icon: envelope
        href: mailto:sicam.iee.usp@gmail.com
  navbar:
    logo: "img/logo_sem_texto.jpg" 
    right:
      - text: "Página inicial"
        href: "https://sicam.com.br"
      - text: "Sobre o SICAM"
        menu:
          - sobre-o-evento.qmd
          - equipe.qmd
          - edicoes-anteriores.qmd
      - text: "V SICAM"
        menu:
          - submissao.qmd   
          - grupos-tematicos.qmd 
          - submissoes-aprovadas.qmd
          - programacao.qmd
          - informacoes.qmd  
      - text: "Anais V SICAM"
        href: "/anais-v-sicam.pdf"        
      # - text: "Inscreva-se"
      #   href: "https://forms.gle/gpKEwHUSp4buPav17"

                
      
    left:
      - icon: house
        href: "https://sicam.com.br"
      - icon: instagram
        href: https://www.instagram.com/sicam_procam_usp/
      - icon: linkedin
        href: "https://www.linkedin.com/in/v-sicam-simp%C3%B3sio-interdisciplinar-de-ci%C3%AAncia-ambiental-a84079319/"
      - icon: envelope
        href: mailto:sicam.iee.usp@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css


editor: visual

lang: pt