---
title: "Grupos temáticos"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

Nesta quinta edição, o SICAM conta com 11 grupos temáticos.

Acesse a página sobre [submissão de trabalhos](submissao.qmd) para saber mais sobre como submeter seu trabalho.

## Eixo 1 - Conservação e Desenvolvimento Socioambiental

#### GT 1: Ecologia Política, Decolonialidade e Justiça Climática

-   **Coordenação:** [Pedro Roberto Jacobi](http://lattes.cnpq.br/6799067928413168)
-   **Descrição:** Aprofundar o olhar para abordagens críticas sobre os conflitos socioambientais pela perspectiva da Ecologia Política, com enfase em trabalhos que compartilhem reflexões sobre decolonialidade e apresentem a problemática da Justiça Climática em suas múltiplas escalas e territorialidades.

#### GT 2: Povos e Comunidades Tradicionais e Originárias: a integração do saber local e da ciência

-   **Coordenação:** [Roberto Adrian Ribaric](http://lattes.cnpq.br/8963365713272264)
-   **Descrição:** Em breve!

#### GT 3: Cidades Resilientes e Planejamento Urbano

-   **Coordenação:** [Guilherme Dias Pereira](http://lattes.cnpq.br/0552367482771773)
-   **Descrição:** Refletir sobre o papel das cidades para o enfrentamento do colapso socioambiental, promovendo a discussão de questões relacionadas à vulnerabilidades socioambientais, desigualdade, políticas públicas e gestão ambiental no processo de produção do espaço urbano

#### GT 4: Produção, Consumo e Resíduos Sólidos

-   **Coordenação:** [Gina Rizpah Besen](http://lattes.cnpq.br/8550871208092441)
-   **Descrição:** Promover um diálogo sobre o ciclo de produção, consumo e a destinação de resíduos sólidos, abordando os impactos sociais e ambientais associados, bem como estratégias de governança e políticas públicas.

#### GT 5: Governança e Uso dos Recursos Naturais

-   **Coordenação:** [Lia Helena Monteiro de Lima Demange](http://lattes.cnpq.br/3773302272955782)
-   **Descrição:** Discutir temáticas relacionadas à governança ambiental e seus desafios frente às disputas pela apropriação da natureza. Promover um diálogo de saberes por meio da participação de diversos agentes políticos.

#### GT 6: Economia Ecológica e Impactos Socioecológicos

-   **Coordenação:** [Bruno Portes](http://lattes.cnpq.br/2925874925850682)
-   **Descrição:** Promover um debate sobre a relação econômica e as suas consequências ambientais e a relação com a governança, tanto sob os pressupostos da Economia Ambiental quanto da Economia Ecológica. Promover um diálogo atual sobre este tema sob a perspectivas socioecologicas e de valores.

## Eixo 2 - Governança, Políticas e Impactos Socioambiental

#### GT 7: Políticas Públicas e Direito Socioambiental

-   **Coordenação:** [Ana Paula Fracalanza](http://lattes.cnpq.br/2494379445883981)
-   **Descrição:** Discutir temáticas relacionadas à formulação, implementação, avaliação e financiamento de políticas ambientais, assim como a gestão de políticas públicas em múltiplas escalas geográficas e níveis. Estabelecer um diálogo sobre a governança dos recursos naturais, considerando tanto os princípios da Economia Ambiental quanto da Economia Ecológica e abordar o ciclo de extração, produção, consumo e descarte de resíduos.

#### GT 8: Comunicação, Educação Climática e Enfrentamento à desinformação

-   **Coordenação:** [Eduardo Geraque](http://lattes.cnpq.br/7131696220835072)
-   **Descrição:** Debater o enfrentamento à desinformação e discutir a compreensão do conceito das Fake News. Na seara socioambiental, abordar caminhos para que a comunicação possa colaborar com o enfrentamento da crise climática e todos os seus desdobramentos na sociedade.

#### GT 9: Transformações Tecnológicas para a Ciência Ambiental

-   **Coordenação:** [Massimo Di Felici](http://lattes.cnpq.br/9759944648465918)
-   **Descrição:** Em breve!

## Eixo 3 - Análise Sociotécnica e Modelagem Socioambiental

#### GT 10: Geotecnologias e Modelagem em Ciência Ambiental

-   **Coordenação:** [Jose Alberto Quintanilha](http://lattes.cnpq.br/1334398456531126)
-   **Descrição:** Em breve!

#### GT 11: Inovação, Transformações e Transições para a Sustentabilidade

-   **Coordenação:** [Célio Bermann](http://lattes.cnpq.br/4429686299726303)
-   **Descrição:** Analisar fenômenos relacionados a ciclos biogeoquímicos, mudanças climáticas, dinâmicas de uso e ocupação do solo, dinâmicas oceânicas e transição energética, associados aos avanços tecnológicos e suas implicações socioambientais, a partir de inovações de engenharia e de geotecnologia fundamentadas nos ODS.
