---
title: "I SICAM - I Simpósio Interdisciplinar de Ciência Ambiental"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<center> <a href="/anais-i-sicam.pdf" target="_blank"><button type="button" class="btn btn-success">Confira os Anais do I SICAM! </button></center></a>




**Data:** 03 à 06 de dezembro de 2013

**Local:** Instituto de Energia e Ambiente da USP

**Texto presente nos anais do evento:**

>   Diversas inquietudes científicas e sociais se apresentavam ao corpo discente do Programa de
Pós Graduação em Ciência Ambiental (PROCAM), o que levou quatro pós – graduandos integrantes
da representação discente do programa a conceber após intensas reflexões conjuntas, O I SICAM,
que ocorreu entre os dias 03 e 06 de dezembro de 2013. Apoiados pelo corpo docente e direção do
Instituto de Energia e Ambiente, foi possível reunir neste evento diversas experiências criativas, em
um ambiente colaborativo, empreendedor de talentos científicos e congregador do corpo crítico
atuante na Ciência Ambiental brasileira em nível de Pós Graduação, já que poucos eventos voltados
para a interdisciplinaridade (uma das áreas mais recentes da CAPES), ocorreram até este momento. <br><br>
As mesas redondas foram compostas por renomados pesquisadores da Ciência Ambiental: Luiz
Carlos Beduschi Filho, Pedro Roberto Jacobi, Ildo Luis Sauer, Arlindo Philippi Jr., Waldir
Mantovani, Silvia Helena Zanirato, Eduardo de Lima Caldas, Cristina Adams, Yara Schaffer Novelli,
Humberto Ribeiro da Rocha e Paulo Sinisgalli. Foram abordados os aspectos conceituais da Ciência
Ambiental no Brasil, suas questões sócioambientais relacionadas à segurança alimentar e
desenvolvimento dos territórios rurais; as mudanças climáticas e suas consequências na
biodiversidade, saúde humana; a economia ecológica e suas diferentes ferramentas de valoração dos
recursos naturais com foco na conservação e apresentação de alternativas, seja na face do manejo e
administração desses recursos, ou seja, na crítica às políticas públicas que realmente promovam a
sustentabilidade ecológica, econômica, social e cultural, bem como a área da modelagem ecológica e
socioambiental (uma das linhas de pesquisa em destaque no PROCAM, mas ainda bastante recente
no país). <br><br>
O evento planejado inicialmente para ser local, dado a qualidade de seu programa, dos docentes
participantes, da diversidade dos temas e do evento ter sido gratuito (não se cobrou taxa de
inscrição), passou a ter visibilidade nacional, contando com a participação de pós-graduandos de todo
o país e também de cinco países latino americanos. Além disso, outro destaque foi a participação de
ouvintes de graduação de diversos cursos e instituições, como a UNB, UFC, UFBA, UEL, UFSC,
UFABC, UNIFESP, que vinham em busca de contatos potenciais para uma futura pós – graduação
nos programas do IEE (PROCAM E PPGE), inspiração e colaboração em trabalhos e até na
organização de mais eventos interdisciplinares nestas diferentes instituições, já que essa é uma
demanda crescente no país. Outro diferencial foi a transmissão e gravação ao vivo, online e gratuita,
pelo site IPTV-USP, permitindo que qualquer pessoa em qualquer lugar do mundo, pudesse acompanhar e participar do evento. Em 3 dias, foram mais de 700 visitas ao SICAM, contabilizando
portanto, aproxidamente 1000 participantes, o que foi um resultado surpreendente, a considerar que a
concepção e organização do evento era de 4 pós graduandos e alguns voluntários itinerantes. <br><br>
O SICAM foi pensado para promover uma experiência em seus participantes que refletissem a
função social da Universidade Pública, que tem como tripé o ensino, a pesquisa e a extensão, ou seja,
como o conhecimento se expande para a comunidade e têm nos seus pós – graduandos a força motriz
de inovação, reflexão e criatividade dentro da academia, essencial ao crescimento de um país. Por
isso, além da programação acadêmica, o evento também apresentou um novo formato de coffe break,
com alimentos orgânicos, locais e provenientes da agricultura familiar (pago através de
financiamento colaborativo). A combinação dos alimentos e bebidas foi pensada para que sua
ingestão pudesse ser escolhida pelo partipante e feita diretamente com as mãos mesmo sendo natural,
com tempo suficiente para que eles pudessem se alimentar com calma e ampliar suas relações com os
demais participantes. Durante o coffee break, houve também uma feira de produtos orgânicos, com a
presença dos produtores, na qual além da venda de seus produtos, ocorreu o marco da entrada da
agricultura orgânica familiar dentro da universidade, o que é muito positivo para o crescimento desse
setor, especialmente diante de potenciais formadores de opinião, além de ser outra forma de se
praticar a extensão dentro da academia. Outras experiências muito interessantes foram a oficina de
grafite, que elaborou um painel coletivo dos pós-graduandos, durante a festa de encerramento, cuja
banda musical contava com alunos da EACH – USP e docentes do PROCAM. <br><br>
Este compêndio de trinta e seis escritos científicos é somente um dos processos
emergentes do SICAM. São trabalhos que exploram as mais variadas experiências, sob diversos
enfoques e centrados no debate da sustentabilidade dos processos socioambientais, culturais, políticos
e econômicos. Mais que um resultado em si, o SICAM mostrou que a Ciência Ambiental se
consolida no debate acadêmico devido ao seu lócus de análise centrado na promoção da
interdisciplinaridade e voltado à compreensão e resolução de questões socioambientais complexas.
Por fim, acreditamos assim que, ao se plantar sementes, em um espaço com liberdade criativa, uma
nova ciência e universidade ou um novo caminho para elas, pode surgir.
<br><br> <center>
Clara Ribeiro Camargo <br>
Fernanda Susi Luccas <br>
Joaquim Alves da Silva Jr. <br>
Juliana Ribeirão de Freitas <br>
<b>Organizadores do I-SICAM</b>
</center>






## COMISSÃO ORGANIZADORA

Clara Ribeiro Camargo

Fernanda Susi Luccas

Joaquim Alves da Silva Jr.

Juliana Ribeirão de Freitas
