---
title: "II SICAM - II Simpósio Interdisciplinar de Ciência Ambiental"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<center> <a href="/anais-ii-sicam.pdf" target="_blank"><button type="button" class="btn btn-success">Confira os Anais do II SICAM! </button></center></a>


Texto obtido no [site do IEE/USP](http://www.iee.usp.br/?q=pt-br/evento/ii-sicam-ii-simp%C3%B3sio-interdisciplinar-de-ci%C3%AAncia-ambiental):

**Tema:** Perspectivas dos Estudos Interdisciplinares frente ao tema da Governança Ambiental e do Desenvolvimento Sustentável

**Data:** 14, 15 e 16 setembro 2016

**Local:** Instituto de Energia e Ambiente da USP

O II Simpósio Interdisciplinar em Ciência Ambiental tem a intenção de refletir sobre os desafios que se apresentam na atualidade no que diz respeito à governança e conservação dos ambientes na perspectiva interdisciplinar e do desenvolvimento sustentável. Pensado a partir do ambiente da academia, pretende discutir como produtores do conhecimento, fazedores de políticas e experimentadores, nas suas mais diversas formas (agricultores, pescadores, indígenas, entre outros), vem produzindo mudanças nas suas relações com o ambiente para alcançar a sustentabilidade.

## OBJETIVO

Discutir as perspectivas dos estudos interdisciplinares frente aos temas da governança ambiental e do desenvolvimento sustentável por meio da produção científica recente e das práticas inovadoras em torno dessa temática.

## JUSTIFICATIVA

O campo da ciência que reúne uma gama de qualificações como ambientais, sustentável, sustentabilidade, entre outros, e que discute as ações humanas com impacto nos ambientes (naturais e humanos), vem há algumas décadas produzindo conhecimentos na tentativa de viabilizar, compreender e responder a muitos dos desafios que a sociedade contemporânea vem produzindo, resultado do desenvolvimento baseado na intensa exploração dos recursos naturais e humanos. Esses desafios caracterizam-se pela sua complexidade e intensidade e exigem uma nova forma de produzir ciência, definida como interdisciplinar.

Ainda que o termo tenha sido incansavelmente debatido e que a institucionalidade não tenha se adequado plenamente a sua operacionalização, um olhar mais atento sobre os resultados dos trabalhos que se pretende sob a sombra dessa grande copa -- interdisciplinaridade -- necessitam ser constantemente revisitados na busca de refletir sobre suas práticas, reformulações e inovações. Isso porque, parece haver um consenso que vivenciamos há algum tempo um turning point, seja na vida cotidiana, na política e/ou na ciência. Tão importante quanto o caminho que escolhermos trilhar, são os resultados que colhemos nesse caminho.

Nesse sentido, a questão que nos estimula é: vivenciamos também esse momento na ciência? Em que medida e como estamos respondendo aos desafios e às mudanças evidentes de uma sociedade em transformação? Como a ciência responde as questões em torno da governança, conservação e desenvolvimento e como tem influenciado os decision makers? Há avanços no campo da ciência e das práticas que apoiem uma nova matriz de desenvolvimento?

## Grupos Temáticos (GTs)

- GT 1 – GOVERNANÇA
  - SUBGRUPO 1 – GOVERNANÇA E DIREITO
  - SUBGRUPO 2 – CLIMA
  - SUBGRUPO 3 – ÁGUA
  - SUBGRUPO 4 – POLÍTICAS PÚBLICAS
  
- GT 2 – DESENVOLVIMENTO SUSTENTÁVEL
  - SUBGRUPO 1 – CONCEITO
  - SUBGRUPO 2 – METODOLOGIA
  - SUBGRUPO 3 – TERRITÓRIO E CIDADANIA
  - SUBGRUPO 4 – SUSTENTABILIDADE E EDUCAÇÃO
  - SUBGRUPO 5 – RECURSOS NATURAIS E ALTERNATIVAS DE USO
  
## PÚBLICO ALVO

Estudantes de graduação, pós-graduação (especialização, mestrado e doutorado), pesquisadores, professores, e agentes governamentais, especialmente os interessados que se identificarem com a temática do evento. Espera-se especial participação de pós-graduandos que realizem seus estudos nos diversos cursos interunidades e interdisciplinares.

## METODOLOGIA

O evento estará organizado a partir de uma Mesa de Diálogo em torno dos dois eixos temáticos principais, com a participação de pesquisadores/professores, formuladores de políticas públicas e sociedade civil organizada. A mesa será estimulada a dialogar com os trabalhos que serão apresentados no GT (Grupo Temático).

O tema da mesa terá a pretensão de ter foco mais generalista e o GT mais específico, tratando de resultados de trabalhos científicos com foco em determinados recursos, temas ou ambiências. Nessa direção, os GTs ocorrerão primeiro e as duas mesas na sequência. O fechamento do evento acontecerá com a Conferência de encerramento.

## COMISSÃO ORGANIZADORA

Adilson Pio da Trindade Júnior, Doutorando do PROCAM/IEE/USP

Izabela Penha de Oliveira Santos, Mestranda do PROCAM/IEE/USP

Livia Preti Boechat, Mestranda do PROCAM/IEE/USP

Suenia Cibeli Ramos de Almeida, Doutoranda do PROCAM/IEE/USP

Zenaida Luisa Lauda Rodriguez, Doutoranda do PROCAM/IEE/USP

Evandro Mateus Moretto, Coordenador do PROCAM/IEE/USP
