---
title: "Sobre o SICAM"
title-block-banner: true
---

O Simpósio Interdisciplinar de Ciência Ambiental (SICAM) é um evento organizado pelo [**Programa de Pós-Graduação em Ciência Ambiental (PROCAM)**](https://procam.iee.usp.br/pt/) do [Instituto de Energia e Ambiente da USP](http://www.iee.usp.br/?q=pt-br), com o objetivo de promover a integração das diversas frentes que regem a Ciência Ambiental e também dos diversos profissionais que atuam nesta área do conhecimento.

O SICAM já teve 4 [edições anteriores](edicoes-anteriores.qmd). Este ano, de 21 a 23 de outubro de 2024, será a quinta edição do Simpósio Interdisciplinar de Ciência Ambiental, o V SICAM, cujo tema principal será: **“Emergência climática na América Latina”**. Além disso, contará com mesas redondas, palestras e apresentação de trabalhos.

O V SICAM é gratuito, em formato presencial, e encoraja a participação de toda a comunidade de pessoas interessadas no debate ambiental, em diferentes áreas de atuação, de dentro e de fora da universidade.

Contamos com a sua participação!

## Local

O evento será 100% presencial, no Instituto de Energia e Ambiente da Universidade de São Paulo (IEE/USP).

**Endereço:** Avenida Professor Luciano Gualberto, 1289, Cidade Universitária CEP 05508-010 - Butantã - São Paulo.

<center>
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14629.169417788255!2d-46.7333307!3d-23.5579413!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce5616b27b7ba5%3A0xbf3891c8c2f7a2cf!2sInstitute%20of%20Electrotechnics%20and%20Energy%20of%20the%20University%20of%20S%C3%A3o%20Paulo!5e0!3m2!1sen!2sbr!4v1725023110255!5m2!1sen!2sbr" width="80%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></center>
