---
title: "Submissão de trabalhos"
title-block-banner: true
toc: true
---

## Calendário de submissão

| Data | Descrição|
|------------|----------------------------------|
| 05/08/2024 | Abertura das submissões de trabalhos |
| 26/08/2024 | Prazo final para submissão de trabalhos |
| 20/09/2024 | Divulgação dos resultados dos trabalhos submetidos |
| 11/10/2024 | Data limite para inscrição de autores que apresentarão os trabalhos aprovados |


## Sobre a submissão


As pessoas interessadas em participar do evento terão a opção de submeter seus trabalhos em forma de **apresentação oral** ou **apresentação de pôster**, distribuídos em **[Grupos Temáticos (GTs)](grupos-tematicos.qmd)**.

<center><a href="/grupos-tematicos.qmd" ><button type="button" class="btn btn-info">Confira os Grupos Temáticos </button></center>

</a>

Os trabalhos, a serem divulgados pelos participantes, envolverão aspectos sociais, econômicos, tecnológicos, urbanos, rurais, ambientais, dentre outros que englobam a interdisciplinar temática ambiental. A divulgação dos trabalhos busca maior integração não apenas com o meio acadêmico, mas também entre profissionais que atuam nas diversas frentes que envolvem o meio ambiente.

### Apresentação Oral

Durante as apresentações, haverá debatedores e relatores.

-   Debatedores: farão perguntas e contribuições sobre os trabalhos apresentados.

-   Relatores: responsáveis por compilar os pontos principais de cada discussão e por expô-los na Plenária Geral a todo público do evento, de modo a trazer maior integração dos temas apresentados entre os GTs.

### Apresentação em Pôster

As apresentações em pôster acontecerão no Centro de Convivência do IEE, durante os dias do evento, em horários que serão divulgados na programação.

Acesse o [template para o pôster](https://github.com/sicam-iee-usp/site-sicam-v2/raw/main/template_poster.pptx).



## Normas de elaboração de resumo expandido

O resumo expandido deverá conter no mínimo **1.000 palavras** e no máximo **1.500** palavras (excluindo as referências, figuras e tabelas), ressaltando a importância e justificativa do trabalho, o objetivo, o local de realização, a metodologia utilizada, os principais resultados e, ao final, a principal conclusão, escritos de maneira clara, coerente e concisa. O conteúdo deve apresentar coerência metodológica.

O **Texto principal** (Desenvolvimento do trabalho, por exemplo, as seções Introdução, Material e Métodos, Resultados, Discussão e Conclusão, podendo-se utilizar outra estrutura caso o autor prefira) deve ser redigido em português, fonte Times New Roman, tamanho 12, formato do papel A4, com espaçamento simples,  margens superior e esquerda de 2,5 cm e inferior e direita de 2,5 cm. O texto deverá ser digitado em modo "justificado". Solicitamos que utilizem o [template de envio](https://github.com/sicam-iee-usp/site-sicam-v2/raw/main/template_submissao.docx) preparado.


Todos os tópicos (Resumo, Introdução, etc) deverão ser escritos em letras maiúsculas e em negrito, seguidos por dois pontos (:) e pelo texto, com início na mesma linha. O recuo do parágrafo deve ser de 1,25 cm. Os tópicos devem ser separados do final do texto anterior por por um ENTER, com espaçamento de 1,5 cm entre as linhas. **Não colocar o número das páginas** no arquivo.

O resumo expandido poderá conter até 5 elementos não textuais (gráficos, imagens, quadros e desenhos), os quais devem seguir as regras do item "Elementos não textuais", que está ao final deste arquivo. Todos os elementos não-textuais devem ser citados no texto principal.

Para facilitar a formatação dos trabalhos pelos autores, a Comissão Organizadora do V SICAM também disponibilizou um template para a submissão:

<center><a href="https://github.com/sicam-iee-usp/site-sicam-v2/raw/main/template_submissao.docx" target="_blank"><button type="button" class="btn btn-info">Clique aqui para acessar <br> o template de submissão</button></center>

</a>

### Sequência de tópicos do Resumo expandido

O **Título** deve ser redigido em fonte Times New Roman, tamanho 12, em negrito e centralizado. Todas as letras do título devem ser maiúsculas.

Após uma linha (espaços 1,5) do título, devem aparecer os **nomes dos autores**, separados por ponto e vírgula, em fonte Times New Roman, tamanho 12, centralizados, nomes e sobrenomes com a primeira letra em maiúsculo. Os **números sobrescritos** correspondentes, demonstrarão o nome completo, instituição e endereço eletrônico do primeiro autor. Colocar as informações de cada autor uma embaixo da outra em espaço simples, centralizado, sendo utilizada a fonte Times New Roman, tamanho 8.

Após a descrição dos autores e antes do texto principal, o material deverá apresentar os itens **Resumo** (máximo de 250 palavras), **Palavras-Chave** (no máximo 5), **Abstract** (máximo de 250 palavras) e **Keywords** (no máximo 5). 

Posteriormente, deve ser apresentado o texto principal (**Desenvolvimento do trabalho**), segundo as regras mencionadas no segundo parágrafo.

Os **Agradecimentos**, se for o caso, devem ser inseridos de forma sucinta, após a conclusão.

Em seguida, apresentar as **Referências**, as quais devem seguir a norma da ABNT, (NBR 6023:2018), sendo que devem ser incluídas apenas aquelas mencionadas no texto e em tabelas, gráficos, fotos ou imagens, aparecendo em ordem alfabética e em letras maiúsculas. Evitar referências de resumos, trabalhos não publicados e comunicação pessoal.

## Elementos não-textuais (máximo de 5)

**Figuras (fotos, gráficos, desenhos):** Devem ser centralizadas, convertidas para o formato "jpg" antes de serem inseridas no texto do Word (inserir, figura, do arquivo). A numeração deve ser sucessiva em algarismos arábicos (Exemplo: Figura 1), sendo citada anteriormente no texto principal. Os **gráficos** devem ser inseridos no texto do Word como figuras (copiar, colar especial, figura do Excel Objeto) e centralizados. Os gráficos devem ser apresentados sem bordas, sendo os eixos x e y com 1/2 pt, descritos com o mesmo tipo e tamanho de letras contidas no texto e a legenda na posição inferior do mesmo. 

**Tabelas:** Devem ser digitadas no texto do Word, de modo a ficarem independentes dos aplicativos fontes, tais como Excel. Espaçamento simples entre linhas. A numeração deve ser sucessiva em algarismos arábicos (Exemplo: Tabela 1), sendo citada anteriormente no texto principal. A legenda deve ser superior à tabela, centralizada, fonte Times New Roman, tamanho 10.

## Orientações para envio de resumo expandido

No ato da submissão do resumo expandido, deverão ser enviados dois arquivos: um em **formato \*.pdf sem os nomes dos autores** (para permitir a avaliação cega por parte dos avaliadores) e outro em **formato word** (\*.doc ou \*.docx) **com os nomes e filiações** dos autores (este será publicado nos anais no caso de aceite).

Cada um destes dois arquivos devem possuir o mesmo nome e com palavras separadas por underscore ("\_"), por exemplo, "Ciencia_Ambiental_SICAM.docx" (para o arquivo com nomes e afiliações dos autores) e "Ciencia_Ambiental_SICAM.pdf" (para o arquivo sem nomes e afiliações dos autores).

Ambos os arquivos devem ser anexados ao **Formulário de submissão** (Link: <https://forms.gle/zaMigRcPrdnrvyNC7> ) até às 23h59min do dia 26 de agosto de 2024. 

<center><a href="https://forms.gle/zaMigRcPrdnrvyNC7" target="_blank"><button type="button" class="btn btn-info">Acesse o formulário de <br> submissão! </button></center></a>


O **limite** máximo de trabalhos submetidos é de **3 (três) resumos expandidos por primeiro autor**, não sendo cobrada qualquer taxa para submissão de trabalhos nem para a participação do evento. O número máximo de autores é de quatro autores por resumo expandido. Em caso de optar por apresentação oral ao vivo para mais de um trabalho, GTs diferentes podem ser considerados desde que ocorram em dias diferentes do evento.

Recomenda-se aos autores que **evitem submissões em última hora** para evitar possíveis falhas de sistema ocasionadas por congestionamento (grande quantidade de usuários ao mesmo tempo).

Em caso de dúvidas, escrever para a Comissão Organizadora do V SICAM, por meio do e-mail [**sicam.iee.usp\@gmail.com**](mailto:sicam.iee.usp@gmail.com).

No ato da submissão, o autor deverá escolher a forma de apresentação oral do seu trabalho: com 10 minutos para exibição e 5 minutos para resposta às perguntas dos participantes; ou na forma de pôster.


Caso a quantidade de apresentações orais exceda a quantidade de tempo disponível para o evento, a Comissão Científica selecionará alguns trabalhos para serem apresentados em formato de pôster.

Uma vez submetido o resumo, não haverá mais oportunidades para qualquer tipo de correção. Ou seja, **o(s) autor(es) é(são) responsável(is) por eventuais erros presentes no seu trabalho**, devendo estar ciente que a qualidade do texto (gramática, ortografia e formatação) será considerada como critério de avaliação pela comissão científica.

**Os certificados de apresentação serão enviados somente aos que apresentaram o trabalho.**

A pessoa que submeteu o resumo já estará inscrita no evento. Contudo, caso esta não seja a pessoa que irá apresentar, a inscrição no evento (para autores que apresentarão trabalhos) poderá ser feita após o resultado do parecer do trabalho submetido, que ocorrerá até o dia 20/09/2024. **O autor responsável pela apresentação deverá se inscrever no evento**. Caso o autor responsável pela apresentação tenha algum imprevisto e não possa participar do evento, o mesmo deverá solicitar que outro autor faça a inscrição para a apresentação ou deverá informar à Comissão Organizadora que o trabalho não será apresentado.
