---
title: "Submissões aprovadas"
title-block-banner: true
toc: true
---

## Eixo 1 - Conservação e Desenvolvimento Socioambiental

#### GT 1: Ecologia Política, Decolonialidade e Justiça Climática

-   Ana Felicien - AS PRÁTICAS ALIMENTARES DE COMUNIDADES QUILOMBOLAS NA AMAZÔNIA NO DEBATE SOBRE MUDANÇAS CLIMÁTICAS

-   Bárbara Oliveira de Morais - RACISMO AMBIENTAL E INJUSTIÇA SOCIOAMBIENTAL: UM OLHAR A PARTIR DAS INTERSECÇÕES DE GÊNERO, RAÇA E CLASSE

-   Gabriela Simões Garcia - Possibilidades da Inovação Ecossocial a partir da Pesquisa-Ação

-   Isabela Carmo Cavaco - A EXPANSÃO DO MOVIMENTO JOVEM POR JUSTIÇA CLIMÁTICA: UM ESTADO DA ARTE PRELIMINAR

-   Leticia Costa de Oliveira Santos - CULTIVANDO O CUIDADO ENTRE CORPOS, PODER E CONFLITO EM UMA HORTA COMUNITÁRIA URBANA

-   Lívia Ananda do Carmo - Em Torno do Desenvolvimento: Estudos de Propostas Fundadas no Conceito de Bem Viver

#### GT 2: Povos e Comunidades Tradicionais e Originárias: a integração do saber local e da ciência

-   Aline Nunes dos Santos - DESAFIOS À GESTÃO AMBIENTAL: AS POTENCIALIDADES DO DIÁLOGO ENTRE A CIÊNCIA MODERNA E CONHECIMENTOS TRADICIONAIS NA CONSERVAÇÃO DA NATUREZA

-   Carlos Potiara Ramos de Castro - Protocolos de consulta e políticas públicas para a sociobiodiversidade na Amazônia

-   Celina Bernardo Padilha - CONFLITOS E TERRITORIALIDADES EM COMUNIDADES TRADICIONAIS NO LITORAL PARANAENSE: UMA REVISÃO BIBLIOGRÁFICA

-   Gabriel de Araujo Silva - Intérpretes da Floresta: Comparando florestas antropogênicas da Indigeneidade com a agrofloresta de Ernst Götsch.

-   Maria Julia Hatala Duarte Sallum - CLIMAZON: AVALIANDO AS PERCEPÇÕES DE COMUNIDADES DE PEQUENA ESCALA NA AMAZÔNIA SOBRE AS MUDANÇAS CLIMÁTICAS ATRAVÉS DE UM JOGO SÉRIO

-   Renata Utsunomiya - Povos Indígenas e Impactos Socioculturais de Hidrelétricas na Amazônia Brasileira

#### GT 3: Cidades Resilientes e Planejamento Urbano

-   Alexandre José Dantas do Nascimento - SOLUÇÕES BASEADAS NA NATUREZA (SbN) NAS ÁREAS SUSCETÍVEIS A ENCHENTES NO MUNICÍPIO DE RIO DE JANEIRO A PARTIR DA ANÁLISE DO PLANO DIRETOR E LEIS DE USO E OCUPAÇÃO DO SOLO

-   Isabela Maciel Macedo - ATUAÇÃO DOS GESTORES NA FORMULAÇÃO DE POLÍTICAS PÚBLICAS PARA A RESILIÊNCIA DE SISTEMAS DE TRANSPORTE URBANO

-   Josafá Melo Nogueira - CRESCIMENTO URBANO E A CONSERVAÇÃO DA NATUREZA: UMA ANÁLISE DA CIDADE DE FORTALEZA, CEARÁ

-   Ramilton Gomes Moreira - EXPLORANDO O POTENCIAL DA FOTOGRAFIA NO DESENVOLVIMENTO DA CIÊNCIA AMBIENTAL: PERCEPÇÕES SOBRE RESÍDUOS POLUENTES EM MANGUEZAIS NA FAVELA DE PALAFITAS DIQUE DA VILA GILDA NA CIDADE DE SANTOS -SP

-   Rodrigo Machado - IMPLEMENTAÇÃO DO ZONEAMENTO ECOLÓGICO-ECONÔMICO DO ESTADO DE SÃO PAULO

-   Vítor Soares Miceli - ANÁLISE SOBRE AS AÇÕES ADAPTATIVAS DO PLANO DE AÇÃO CLIMÁTICA DE SÃO PAULO, PLANCLIMA.

-   Yoshua Muriel Souza dos Santos - Desafios Ambientais da Urbanização

#### GT 4: Produção, Consumo e Resíduos Sólidos

-   Jacqueline Zanin Lima - CONTAMINAÇÃO DO SOLO POR ESCÓRIA DE FUNDIÇÃO: EFEITOS NO DESENVOLVIMENTO INICIAL DE MILHO E RÚCULA

-   Jéssica Pelinsom Marques - SORÇÃO DE CHUMBO EM SOLO DO VALE DO RIBEIRA (SP) ANTES E DEPOIS DA ADIÇÃO DE BIOCARVÃO DE RESÍDUOS DE PODA

-   MARIA JOSÉ REIS - GESTÃO DE RESÍDUOS SÓLIDOS NO AEROPORTO DE VIRACOPOS: ANÁLISE DAS PRÁTICAS SUSTENTÁVEIS

-   Mônica Pilz Borba - Caminhos da Compostagem no Brasil e em São Paulo

-   Tainá Ângela Vedovello Bimbati - A DESTINAÇÃO DE RESÍDUOS SÓLIDOS E CATADORES DE MATERIAIS RECICLÁVEIS-UM ENSAIO SOBRE JUSTIÇA AMBIENTAL NO SUL GLOBAL

#### GT 5: Governança e Uso dos Recursos Naturais

-   Clarissa Nogueira Mariotti - GOVERNANÇA E TRANSIÇÕES ENERGÉTICAS JUSTAS EM COMUNIDADE TRADICIONAL CAIÇARA

-   Giovanna Santini Ruta Lopes - Mosaicos de Áreas Marinhas Protegidas como ferramenta integrativa frente às Mudanças Climáticas

-   Juliana Azevedo da Silva - DESENVOLVIMENTO E SUSTENTABILIDADE: ANÁLISE DAS TEORIAS AMBIENTAIS SOB A PERSPECTIVA ECONÔMICA E ECOLÓGICA

-   Marcela Dálete de Moraes Santos - AÇÕES DE COMANDO E CONTROLE SOBRE A PESCA NO LITORAL NORTE DE SÃO PAULO: UM DIAGNÓSTICO DOS AUTOS DE INFRAÇÃO E UMA ANÁLISE DOS BOLETINS DE OCORRÊNCIA

-   Maria Julia Hatala Duarte Sallum - DA LAMA AO CAOS, DO CAOS À LAMA: O MÉTODO WORLD CAFÉ COMO FERRAMENTA PARA ENGAJAR A PARTICIPAÇÃO SOCIAL DE PESCADORES ARTESANAIS NA TRANSFORMAÇÃO DE UM CONFLITO SOCIOAMBIENTAL NA BAIXADA SANTISTA

-   Nicole Russo Guerrato - POLÍTICAS AMBIENTAIS PARA A CONSERVAÇÃO DA BIODIVERSIDADE DA AMAZÔNIA AZUL

-   Rodrigo Santana Cardoso - DESDOBRAMENTOS DE UMA GOVERNANÇA NÃO INCLUDENTE: A EMERGÊNCIA DOS RISCOS À PESCA ARTESANAL NA BAIXADA SANTISTA

-   Sofia Brito Lourenço - EXPLORANDO AS CONTRIBUIÇÕES DA NATUREZA PARA AS COMUNIDADES NO MOSAICO DE ILHAS E ÁREAS MARINHAS PROTEGIDAS DO LITORAL PAULISTA (MIAMP)

#### GT 6: Economia Ecológica e Impactos Socioecológicos

-   CLAUDIO ANGELO CORREA GONZAGA - Valoração e compensação ecológica dos danos ambientais causados pelo desmatamento ilegal

## Eixo 2 - Governança, Políticas e Impactos Socioambiental

#### GT 7: Políticas Públicas e Direito Socioambiental

-   Aline Lis Ramos Pereira - O MUNDO DA VIDA E O ESGOTAMENTO SANITÁRIO EM UBATUBA-SP

-   Ana Claudia de Almeida - MUDANÇA INSTITUCIONAL E FINANCIAMENTO DA ADAPTAÇÃO CLIMÁTICA – ANÁLISE DO FUNDO INTERNACIONAL PARA DESENVOLVIMENTO AGRÍCOLA

- Livia Ferreira Pugliesi -	APLICAÇÃO DOS CONCEITOS DE DESCARBONIZAÇÃO E RETROFIT NA CONSTRUÇÃO CIVIL A PARTIR DA TRANSFORMAÇÃO AMBIENTAL

-   Luiz Guilherme Ferreira Pires - Deliberação ou manipulação? Esvaziamento da Participação Social no Conselho Gestor de ZEIS do Jardim Keralux em face à Adaptação Climática

-   Radmila Gravato Rodrigues - Análise dos dados do Índice de Desenvolvimento Sustentável de cidades (Brasil 2023) e sua correlação com o Índice de Desenvolvimento Humano

#### GT 8: Comunicação, Educação Climática e Enfrentamento à desinformação

-   Amanda Cseh - MUDANÇAS E JUSTIÇAS CLIMÁTICAS NO CONTEXTO ESCOLAR: CONHECIMENTOS, INTERESSES, OPORTUNIDADES E DESAFIOS EM ESCOLAS MUNICIPAIS DE SÃO VICENTE/SP-BRASIL

-   Rolf Dieringer - Vigilantes-da-chuva-Petropolis

#### GT 9: Transformações Tecnológicas para a Ciência Ambiental

-   Isis Preti Passarelli - “De olho na lama” – Aplicativo como ferramenta de monitoramento participativo no território pesqueiro da Baixada Santista

## Eixo 3 - Análise Sociotécnica e Modelagem Socioambiental

#### GT 10: Geotecnologias e Modelagem em Ciência Ambiental

-   JOSEPH HARARI - SOBRE O SISTEMA DE ALERTA PARA RESSACAS E INUNDAÇÕES COSTEIRAS PARA O ESTADO DE SÃO PAULO - SARIC

-   Valéria Vaz Alonso - ESTIMATIVA DA TAXA DE INFILTRAÇÃO DE ÁGUA DE CHUVAS EM VERTENTES NA SERRA DA MANTIQUEIRA, BRASIL

#### GT 11: Inovação, Transformações e Transições para a Sustentabilidade

**Em breve**
